### ISSUE TITLE
Android NullReferenceException

### ISSUE THREAD

**Issue by 14skywalker** [alexrainman/CarouselView#168]
Hi Alex,

There is one situation in which I get a nullref on Android. This is the call stack:
```
at CarouselView.FormsPlugin.Android.CarouselViewRenderer.InsertPage (System.Object item, System.Int32 position) [0x00012] in <a17b7b10a3934a59be9f984b8839ba35>:0 
at CarouselView.FormsPlugin.Android.CarouselViewRenderer+<ItemsSource_CollectionChanged>d__6.MoveNext () [0x0004f] in <a17b7b10a3934a59be9f984b8839ba35>:0 
```
Looking at the code it might be in the first line of InsertPage?
`var Source = ((PageAdapter)viewPager?.Adapter).Source;`

The `viewPager` or the `viewPager.Adapter` might be null. I am still trying to pinpoint the exact circumstances.

**Comment by alexrainman** [comment]
K, if you do, share a repo project. Thanks

**Comment by 14skywalker** [comment]
Hi @alexrainman, Attached is a repo project. Basically when the parent of the carousel is hidden (and was never visible) the error occurs when an item is added. So build and run on android and click 'update carousel'. The error does not occur when you first toggle the visiblity.

[CarouselViewIssue.zip](https://github.com/alexrainman/CarouselView/files/1130323/CarouselViewIssue.zip)

**Comment by alexrainman** [comment]
Fixed. Next release.

**Comment by 14skywalker** [comment]
Hi Alex, Any idea when you will be releasing this fix? Best regards, J.

**Comment by alexrainman** [comment]
It has been released in version 4.4.2

**Comment by 14skywalker** [comment]
Hi Alex, I updated to 4.4.2 but the issue is still there. Sorry...

**Comment by janniklind** [comment]
It seems the same is the case with Replace and Move events.
